application: skalde
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: index.py
- url: /message/.*
  script: index.py
- url: /lib
  static_dir: assets/lib
- url: /html
  static_dir: assets/html
- url: /lib
  static_dir: assets/lib
- url: /css
  static_dir: assets/css
- url: /js
  static_dir: assets/js
- url: /image
  static_dir: assets/image
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /
  static_files: assets/index.html
  upload: assets/index.html
- url: /skalde.js
  static_files: assets/skalde.js
  upload: assets/skalde.js


